version: "3.1"

services:
  pascal:
    build: 
      context: .
      dockerfile: Dockerfile.pascalfc
    volumes:
      - ./unidad_1:/home
  mpi_openmp:
    build: 
      context: .
      dockerfile: Dockerfile.mpi_openmp
    volumes:
      - ./unidad_3:/home
  haskell_prolog:
    build: 
      context: .
      dockerfile: Dockerfile.haskell_prolog
    volumes: 
      - ./unidad_4:/home