version: "3.1"

services:
  pascal:
    build: 
      context: .
      dockerfile: Dockerfile.pascalfc
    volumes:
      - ./unidad_1:/home/curso
  mpi_openmp:
    build: 
      context: .
      dockerfile: Dockerfile.mpi_openmp
    volumes:
      - ./unidad_3:/home/curso